"""Constants for the House Brain Home Assistant integration."""

from typing import Final

DOMAIN: Final = "house_brain"

CONF_BASE_URL: Final = "base_url"
CONF_CONVERSATION_MODE: Final = "conversation_mode"

DEFAULT_BASE_URL: Final = "http://house-brain.local:8090"
DEFAULT_CONVERSATION_MODE: Final = "observe"
DEFAULT_REQUEST_TIMEOUT: Final = 300

CONVERSATION_MODES: Final = ("observe", "simulate", "execute")

ATTRIBUTION: Final = "Responses are generated by the local House Brain service"
